--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "TODAYEAT"."INQUIRY_TBL" cascade constraints;
DROP TABLE "TODAYEAT"."MEMBER_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table INQUIRY_TBL
--------------------------------------------------------

  CREATE TABLE "TODAYEAT"."INQUIRY_TBL" 
   (	"INQUIRY_NO" NUMBER, 
	"INQUIRY_SUBJECT" VARCHAR2(60 BYTE), 
	"INQUIRY_CONTENT" VARCHAR2(2000 BYTE), 
	"INQUIRY_WRITER" VARCHAR2(30 BYTE), 
	"INQUIRY_DATE" DATE DEFAULT SYSDATE, 
	"INQUIRY_YN" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "TODAYEAT"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"MEMBER_PW" VARCHAR2(40 BYTE), 
	"MEMBER_PW_RE" VARCHAR2(40 BYTE), 
	"MEMBER_NAME" VARCHAR2(15 BYTE), 
	"MEMBER_PHONE" VARCHAR2(13 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(150 BYTE), 
	"MEMBER_GENDER" VARCHAR2(6 BYTE), 
	"MEMBER_BIRTHDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TODAYEAT.INQUIRY_TBL
SET DEFINE OFF;
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (20,'5','5','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (17,'2','2','0',to_date('23/08/03','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (18,'3','3','0',to_date('23/08/03','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (19,'4','4','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (21,'6','6','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (22,'7','7','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (23,'8','8','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (24,'9','9','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (25,'10','10','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (26,'11','11','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (27,'12!!','12!!','0',to_date('23/08/04','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (28,'문의1번째','1번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (29,'문의2번째','2번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (30,'문의3번째','3번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (31,'문의4번째','4번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (32,'문의5번째','5번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (33,'문의6번째','6번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (34,'문의7번째','7번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (35,'문의8번째','8번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (36,'문의9번째','9번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (37,'문의10번째','10번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (38,'문의1번째','1번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (39,'문의2번째','2번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (40,'문의3번째','3번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (41,'문의4번째','4번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (42,'문의5번째','5번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (43,'문의6번째','6번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (44,'문의7번째','7번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (45,'문의8번째','8번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (46,'문의9번째','9번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (47,'문의10번째','10번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (48,'문의11번째','11번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (49,'문의12번째','12번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (50,'문의13번째','13번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (51,'문의14번째','14번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (52,'문의15번째','15번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (53,'문의16번째','16번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (54,'문의17번째','17번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (55,'문의18번째','18번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (56,'문의19번째','19번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (57,'문의20번째','20번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (58,'문의21번째','21번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (59,'문의22번째','22번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (60,'문의23번째','23번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (61,'문의24번째','24번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (62,'문의25번째','25번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (63,'문의26번째','26번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (64,'문의27번째','27번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (65,'문의28번째','28번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (66,'문의29번째','29번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (67,'문의30번째','30번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (68,'문의31번째','31번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (69,'문의32번째','32번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (70,'문의33번째','33번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (71,'문의34번째','34번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (72,'문의35번째','35번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (73,'문의36번째','36번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (74,'문의37번째','37번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (75,'문의38번째','38번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (76,'문의39번째','39번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (77,'문의40번째','40번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (78,'문의41번째','41번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (79,'문의42번째','42번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (80,'문의43번째','43번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (81,'문의44번째','44번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (82,'문의45번째','45번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (83,'문의46번째','46번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (84,'문의47번째','47번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (85,'문의48번째','48번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (86,'문의49번째','49번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (87,'문의50번째','50번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (88,'문의1번째','1번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (89,'문의2번째','2번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (90,'문의3번째','3번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (91,'문의4번째','4번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (92,'문의5번째','5번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (93,'문의6번째','6번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (94,'문의7번째','7번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (95,'문의8번째','8번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (96,'문의9번째','9번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (97,'문의10번째','10번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (98,'문의11번째','11번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (99,'문의12번째','12번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (100,'문의13번째','13번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (101,'문의14번째','14번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (102,'문의15번째','15번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (103,'문의16번째','16번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (104,'문의17번째','17번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (105,'문의18번째','18번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (106,'문의19번째','19번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (107,'문의20번째','20번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (108,'문의21번째','21번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (109,'문의22번째','22번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (110,'문의23번째','23번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (111,'문의24번째','24번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (112,'문의25번째','25번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (113,'문의26번째','26번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (114,'문의27번째','27번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (115,'문의28번째','28번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (116,'문의29번째','29번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (117,'문의30번째','30번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (118,'문의31번째','31번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (119,'문의32번째','32번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (120,'문의33번째','33번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (121,'문의34번째','34번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (122,'문의35번째','35번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (123,'문의36번째','36번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (124,'문의37번째','37번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (125,'문의38번째','38번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (126,'문의39번째','39번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (127,'문의40번째','40번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (128,'문의41번째','41번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (129,'문의42번째','42번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (130,'문의43번째','43번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (131,'문의44번째','44번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (132,'문의45번째','45번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (133,'문의46번째','46번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (134,'문의47번째','47번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (135,'문의48번째','48번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
Insert into TODAYEAT.INQUIRY_TBL (INQUIRY_NO,INQUIRY_SUBJECT,INQUIRY_CONTENT,INQUIRY_WRITER,INQUIRY_DATE,INQUIRY_YN) values (136,'문의49번째','49번째 문의','일용자',to_date('23/08/07','RR/MM/DD'),'미등록');
REM INSERTING into TODAYEAT.MEMBER_TBL
SET DEFINE OFF;
Insert into TODAYEAT.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_PW_RE,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS,MEMBER_GENDER,MEMBER_BIRTHDAY) values ('user01','pass01','pass01','일용자','01077771111','user01@naver.com','서울시 강남구','on',to_date('23/08/10','RR/MM/DD'));
Insert into TODAYEAT.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_PW_RE,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS,MEMBER_GENDER,MEMBER_BIRTHDAY) values ('user02','pass02','pass02','이용자','01078975225','user02@naver.com','서울시 강북구','on',to_date('20/01/30','RR/MM/DD'));
Insert into TODAYEAT.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_PW_RE,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS,MEMBER_GENDER,MEMBER_BIRTHDAY) values ('user03','pass03','pass03','삼용자','01054622246','user03@naver.com','서울시 남대문구','on',to_date('17/01/03','RR/MM/DD'));
Insert into TODAYEAT.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_PW_RE,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS,MEMBER_GENDER,MEMBER_BIRTHDAY) values ('user04','pass04','pass04','최이름','01087954465','user04@naver.com','서울시','on',to_date('08/02/27','RR/MM/DD'));
Insert into TODAYEAT.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_PW_RE,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS,MEMBER_GENDER,MEMBER_BIRTHDAY) values ('khuser01','pass01','pass01','김이름','01078654879','khuser01@naver.com','서울시 동대문구','on',to_date('23/08/09','RR/MM/DD'));
Insert into TODAYEAT.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_PW_RE,MEMBER_NAME,MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDRESS,MEMBER_GENDER,MEMBER_BIRTHDAY) values ('user05','pass05','pass05','오용자','01025799876','user05@naver.com','서울','on',to_date('18/08/17','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007323
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODAYEAT"."SYS_C007323" ON "TODAYEAT"."INQUIRY_TBL" ("INQUIRY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007310
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODAYEAT"."SYS_C007310" ON "TODAYEAT"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table INQUIRY_TBL
--------------------------------------------------------

  ALTER TABLE "TODAYEAT"."INQUIRY_TBL" ADD PRIMARY KEY ("INQUIRY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODAYEAT"."INQUIRY_TBL" MODIFY ("INQUIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."INQUIRY_TBL" MODIFY ("INQUIRY_WRITER" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."INQUIRY_TBL" MODIFY ("INQUIRY_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."INQUIRY_TBL" MODIFY ("INQUIRY_SUBJECT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "TODAYEAT"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODAYEAT"."MEMBER_TBL" MODIFY ("MEMBER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."MEMBER_TBL" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."MEMBER_TBL" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."MEMBER_TBL" MODIFY ("MEMBER_PW_RE" NOT NULL ENABLE);
  ALTER TABLE "TODAYEAT"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
